name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: linux
            runner: ubuntu-latest
            binary: filinator
          - os: mac
            runner: macos-latest
            binary: filinator
          - os: windows
            runner: windows-latest
            binary: filinator.exe
    
    runs-on: ${{ matrix.platform.runner }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup development environment (Linux)
        if: matrix.platform.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ninja-build cmake

      - name: Setup development environment (macOS)
        if: matrix.platform.os == 'mac'
        run: |
          brew install ninja cmake

      - name: Setup development environment (Windows)
        if: matrix.platform.os == 'windows'
        run: |
          choco install ninja cmake
          
      - name: Configure build
        run: |
          cmake -B build -G Ninja

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Copy binary to root directory
        run: |
          cp build/filinator${{ matrix.platform.os == 'windows' && '.exe' || '' }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: filinator-${{ matrix.platform.os }}
          path: ${{ matrix.platform.binary }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            artifacts/filinator-linux/filinator
            artifacts/filinator-mac/filinator
            artifacts/filinator-windows/filinator.exe
