name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: linux
            runner: ubuntu-latest
            binary: filinator
          - os: mac
            runner: macos-latest
            binary: filinator

    runs-on: ${{ matrix.platform.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Linux packages
        run: sudo apt install -y clang ninja-build
        if: matrix.platform.os == 'linux'
      - name: Install Mac packages
        run: brew install ninja
        if: matrix.platform.os == 'mac'

      - name: Build
        run: ninja

      - name: Cleanup
        run: ninja -t clean
      
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: |
            Changes in this Release:
            - Add a new feature
            - Fix a bug
          artifacts: ${{ matrix.platform.binary }}
          