name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: linux
            runner: ubuntu-latest
            binary: filinator
          - os: mac
            runner: macos-latest
            binary: filinator
          - os: windows
            runner: windows-latest
            binary: filinator.exe

    runs-on: ${{ matrix.platform.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Windows packages
        run: choco install -y clang ninja
        if: matrix.platform.os == 'windows'
      - name: Install Linux packages
        run: sudo apt install -y clang ninja-build
        if: matrix.platform.os == 'linux'
      - name: Install Mac packages
        run: brew install ninja
        if: matrix.platform.os == 'mac'

      - name: Build
        run: ninja

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ matrix.binary }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ github.ref }}

      - name: Upload Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ${{ matrix.binary }}
          asset_name: ${{ matrix.binary }}
          asset_content_type: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        run: ninja -t clean
