name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        platform:
          - os: linux
            runner: ubuntu-latest
            binary: filinator
          - os: mac
            runner: macos-latest
            binary: filinator
          - os: windows
            runner: windows-latest
            binary: filinator.exe

    runs-on: ${{ matrix.platform.runner }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Windows packages
        run: choco install -y llvm ninja
        if: matrix.platform.os == 'windows'
      - name: Install Linux packages
        run: sudo apt install -y clang ninja-build
        if: matrix.platform.os == 'linux'
      - name: Install Mac packages
        run: brew install ninja
        if: matrix.platform.os == 'mac'

      - name: Build
        run: ninja

      - name: Cleanup
        run: ninja -t clean
